### PR TITLE
Remove all namespaces from code

### PR DESCRIPTION
**Pull request by klieret**

### CODE REVIEW

**Review by graeme-a-stewart — APPROVED** [review]

**Comment by graeme-a-stewart** [comment]
Your change looks great - thank you @klieret. Do you know why the CI failed to build the website?

**Comment by chavid** [comment]
@klieret @graeme-a-stewart I totally approve also.

**Comment by klieret** [comment]
No, it builds fine, it's just that the carpentry's `lesson-check` fails, because there are some additional sanity checks, some of which we could solve, some of which are only annoying (consecutive episode numbers being one -- I think they wanted to relax this one, but haven't merged it. Once they do we need to update our styles repo and then bring it in here etc.)

**Comment by graeme-a-stewart** [comment]
> No, it builds fine, it's just that the carpentry's `lesson-check` fails, because there are some additional sanity checks, some of which we could solve, some of which are only annoying (consecutive episode numbers being one -- I think they wanted to relax this one, but haven't merged it. Once they do we need to update our styles repo and then bring it in here etc.)

OK, thanks for the reminder! To be fixed later then...

**Pull request merged**
